export const DOCS_DIR = 'docs';

export const PROJECT_DOC_FILES = {
  readme: 'Readme.md',
  structure: 'ProjectStructure.md',
  functionBlocks: 'FunctionBlockInfo.md',
  skills: 'SkillInfo.md',
  mcpInfo: 'MCP_Info.md',
} as const;

/**
 * Build the initialization prompt for generating project docs.
 *
 * The agent is expected to:
 * - Use filesystem tools (list_directory, read_file, create_file, apply_patch) inside the agent root.
 * - Use MCP tools (GraphDB, OPC UA, MQTT, etc.) when available.
 * - Create / overwrite markdown files under `<rootDir>/docs`.
 */
export function buildProjectInitPrompt(rootDir: string): string {
  const docsRoot = `${rootDir.replace(/[/\\]$/, '')}/${DOCS_DIR}`;

  return [
    `You are an expert IEC 61499 / PLC and industrial connectivity assistant.`,
    ``,
    `Your task is to **initialize project documentation** for the PLC skills project located at:`,
    `- Project root (agent root): ${rootDir}`,
    ``,
    `Use the available tools to explore the filesystem and connected MCP servers. Then create or overwrite the following markdown files under:`,
    `- ${docsRoot}/${PROJECT_DOC_FILES.readme}`,
    `- ${docsRoot}/${PROJECT_DOC_FILES.structure}`,
    `- ${docsRoot}/${PROJECT_DOC_FILES.functionBlocks}`,
    `- ${docsRoot}/${PROJECT_DOC_FILES.skills}`,
    `- ${docsRoot}/${PROJECT_DOC_FILES.mcpInfo}`,
    ``,
    `# Important constraints`,
    `- Work **inside the agent root directory**; treat relative paths as rooted at ${rootDir}.`,
    `- Use filesystem tools instead of printing large file contents into the chat:`,
    `  - Use \`list_directory\` to inspect folder structures (especially \`IEC61499\`, \`HMI\`, \`HwConfiguration\`, \`AssetLinkData\`, \`Topology\`).`,
    `  - Use \`read_file\` only on representative and important files (\`.fbt\`, CAT/OPC UA XML, key HMI files, configs).`,
    `  - Use \`create_file\` or \`apply_patch\` to write markdown files under \`${DOCS_DIR}/\`.`,
    `- If any of the target docs already exist, **overwrite them completely** with improved content (do not append).`,
    `- Keep docs concise but information‑dense; prefer tables and bullet lists over raw XML or long code dumps.`,
    ``,
    `# Files to create and their content`,
    ``,
    `## 1) ${PROJECT_DOC_FILES.readme} – Project overview`,
    `Location: ${docsRoot}/${PROJECT_DOC_FILES.readme}`,
    `- High‑level description of the FESTO DS skills / IEC 61499 project.`,
    `- Explain the main hardware/modules (feeder, pusher, transfer, etc.) and how IEC 61499 skills control them.`,
    `- Summarize key folders:`,
    `  - \`IEC61499/\` – function blocks, skills, system configuration.`,
    `  - \`HMI/\` – HMI canvases and code‑behind files for skills.`,
    `  - \`HwConfiguration/\`, \`Topology/\`, \`AssetLinkData/\` – hardware and asset metadata.`,
    `- Briefly describe the concept of **BasicSKILL** and higher‑level skills (e.g. skGoToLeft, skTransfer, skPick, etc.).`,
    `- Explain that this \`${DOCS_DIR}/\` folder is the primary entry point for LLM agents to understand the project.`,
    ``,
    `## 2) ${PROJECT_DOC_FILES.structure} – Project folder architecture`,
    `Location: ${docsRoot}/${PROJECT_DOC_FILES.structure}`,
    `- Use \`list_directory\` to inspect the project tree under ${rootDir}.`,
    `- Produce a concise tree or outline of the most important directories and files, for example:`,
    `  - \`IEC61499/\` with subfolders like \`BasicSKILL\`, \`skGoToLeft\`, \`skTransfer\`, \`skPick\`, \`System\`, \`Model\`, \`Configuration\`, \`SnapshotCompiles\`, etc.`,
    `  - \`HMI/\` with subfolders for skills, BasicSKILL HMI, configurations, etc.`,
    `  - \`HwConfiguration/\`, \`AssetLinkData/\`, \`Topology/\`.`,
    `- For each top‑level folder, add a one‑sentence description of its role.`,
    ``,
    `## 3) ${PROJECT_DOC_FILES.functionBlocks} – Function block information`,
    `Location: ${docsRoot}/${PROJECT_DOC_FILES.functionBlocks}`,
    `- Focus on IEC 61499 function blocks under \`IEC61499/\`.`,
    `- Use \`list_directory\` and \`read_file\` (on representative .fbt files) to identify:`,
    `  - **Basic FBs** (with <BasicFB> ECC).`,
    `  - **Composite FBs** (with <FBNetwork> only, often with comments like "Composite Function Block Type").`,
    `  - HMI‑related FBs (e.g. \`*_HMI.fbt\`).`,
    `  - CAT / OPC UA mapping files (\`*_CAT.offline.xml\`, \`*_CAT.opcua.xml\`, etc.).`,
    `- Organize the doc into sections such as:`,
    `  - Basic Function Blocks – table with Name, role/category, key events/data, skills that use them.`,
    `  - Composite Function Blocks – table with Name, internal important FBs, external interface.`,
    `  - CAT / OPC UA mapping – which FB/skill each CAT file belongs to and what it exposes.`,
    `  - HMI‑related FBs and how they relate to skills/HMI canvases.`,
    `- Do **not** paste full XML; summarize structures and behavior.`,
    ``,
    `## 4) ${PROJECT_DOC_FILES.skills} – Skill information (atomic vs composite)`,
    `Location: ${docsRoot}/${PROJECT_DOC_FILES.skills}`,
    `- Focus on skills built on top of BasicSKILL and skill templates under \`IEC61499/\`.`,
    `- Detect skills and classify them as **atomic** or **composite** using heuristics:`,
    `  - Names like \`skGoToLeft\`, \`skTransfer\`, \`skPick\`, \`skPlace\`, etc.`,
    `  - FBs and folders under \`IEC61499/BasicSKILL\` and \`IEC61499/SKILL\`.`,
    `  - FB networks that include \`BasicSKILL\`, \`SKILL_BFB\`, or similar.`,
    `- Document:`,
    `  - **Atomic skills** – Name, classification, key events/IO, short behavior summary (INIT/EXECUTE/RESET/etc.).`,
    `  - **Composite skills** – Name, which atomic/basic skills they use, any internal orchestration FBs, relevant CAT/HMI artifacts.`,
    `  - A brief **generic skill lifecycle** description as implemented by BasicSKILL/SKILL_BFB (INIT → STARTING → EXECUTE → COMPLETING / STOPPING / ABORTING, etc.).`,
    ``,
    `## 5) ${PROJECT_DOC_FILES.mcpInfo} – MCP and PLC integration`,
    `Location: ${docsRoot}/${PROJECT_DOC_FILES.mcpInfo}`,
    `- This is the **key integration document** linking MCPs to PLC code.`,
    `- First, read the repo‑root \`mcp-config.json\` (use \`read_file\`) to discover configured MCP servers:`,
    `  - GraphDB (Graph/ontology MCP).`,
    `  - OPC UA MCP (Python).`,
    `  - MQTT MCP (Python).`,
    `  - Any other MCP entries.`,
    `- For each MCP:`,
    `  - Summarize configuration (command, env vars like \`MCPHUB_SERVER_URL\`, \`OPCUA_SERVER_URL\`, \`MQTT_BROKER_URL\`, Sparkplug IDs, etc.).`,
    `  - When tools are available and the server is reachable, **call MCP tools** to fetch runtime details:`,
    `    - **GraphDB MCP**:`,
    `      - Use SPARQL / graph tools (e.g. a tool that runs SPARQL queries) to discover ontologies, classes, and relationships relevant to skills, devices and IO.`,
    `      - List key ontologies / prefixes and how they represent skills and equipment.`,
    `      - Include a few example SPARQL queries and **summaries** of their results (no huge tables).`,
    `    - **OPC UA MCP**:`,
    `      - Browse NodeIds (using OPC UA tools) to find nodes for skill states (CURRENT_STATE), commands (START, STOP, RESET, etc.) and relevant IO.`,
    `      - Produce tables mapping: Skill/FB → variable/event → OPC UA NodeId → browse path / namespace.`,
    `      - Relate NodeIds back to CAT/OPC UA files under \`IEC61499/\` where possible.`,
    `    - **MQTT MCP**:`,
    `      - Identify important topics and payload structures, especially those tied to skills/states/alarms.`,
    `      - Summarize broker URL, client ID, Sparkplug identifiers, and any discovered topic patterns.`,
    `- Add a dedicated **"PLC–MCP Mapping"** section that cross‑links:`,
    `  - IEC 61499 skills / FBs (from FunctionBlockInfo.md / SkillInfo.md).`,
    `  - GraphDB ontology entities (classes/instances).`,
    `  - OPC UA NodeIds / browse paths.`,
    `  - MQTT topics (where applicable).`,
    `- If a given MCP is configured but not reachable, state clearly that runtime queries failed and fall back to configuration‑only information.`,
    ``,
    `# Tool usage strategy`,
    `- Prefer small, targeted tool calls over dumping huge files.`,
    `- For filesystem inspection, call \`list_directory\` on:`,
    `  - \`IEC61499/\`, \`HMI/\`, \`HwConfiguration/\`, \`AssetLinkData/\`, \`Topology/\`.`,
    `- For content understanding, call \`read_file\` only on key .fbt / .xml / .cs files (e.g., BasicSKILL, representative skills like skGoToLeft, skTransfer).`,
    `- For documentation creation, use \`create_file\` or \`apply_patch\` to write each markdown file under \`${DOCS_DIR}/\`.`,
    `- For MCPs, use the available MCP tools exposed to you by the system (GraphDB, OPC UA, MQTT, etc.) to gather live details where possible.`,
    ``,
    `When you are done, all five markdown files should exist under ${docsRoot} with high‑quality, concise, and cross‑linked content that future agents can rely on to understand the project and its MCP integrations.`,
  ].join('\n');
}

